//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Historytransactions = new HashSet<Historytransaction>();
            this.Items = new HashSet<Item>();
            this.StockingDetails = new HashSet<StockingDetail>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductWeight { get; set; }
        public decimal ProductPrice { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdationTime { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> BarCode { get; set; }
        public Nullable<decimal> StockInPrice { get; set; }
        public Nullable<int> ThreshHold { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Historytransaction> Historytransactions { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<StockingDetail> StockingDetails { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
