//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int TenantId { get; set; }
        public string TenantName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdationTime { get; set; }
    }
}
