//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public string Comments { get; set; }
        public int Count { get; set; }
        public decimal TotalAmount { get; set; }
        public int ProductId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdationTime { get; set; }
        public Nullable<decimal> StockInPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
