//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userdetail
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int Mobile { get; set; }
        public string Address { get; set; }
        public string MaritiualStatus { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
