//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Items = new HashSet<Item>();
            this.StockingDetails = new HashSet<StockingDetail>();
        }
    
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string ProductName { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdationTime { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<StockingDetail> StockingDetails { get; set; }
    }
}
